### ISSUE TITLE
Add luau support

### ISSUE THREAD

**Issue by 0xJWLabs** [CosmicHorrorDev/two-face#27]
Can you add luau support here? or maybe a way to be able to use .add_from_folder from syntect? Thanks!

**Comment by CosmicHorrorDev** [comment]
Thanks for the issue!

As a start you'll need some `Luau.sublime-syntax` file that `syntect` supports (there have been a handful of features added over the years that `syntect` still doesn't support). I've found [this gist](https://gist.github.com/unittensor/56951a8f2daf6616e2005fff6cd4e913) that links to [another gist](https://gist.github.com/unittensor/d6d638615dedb3d0cb5a704df86df6ca) with a syntax file, but there's no license info included, so that should be clarified with the author as well (and I'm not sure if it used any unsupported features)

> Can you add luau support here?

Generally extra syntaxes should be added to the [`bat` repo](https://github.com/sharkdp/bat) although they do have some prerequisites on new syntaxes being added. You can open an issue there to have things tracked

> or maybe a way to be able to use .add_from_folder from syntect?

You can already do this

```rust
two_face::syntax::extra_newlines() // or _no_newlines
    .into_builder()
    // `.add()`or  `.add_from_folder()`
    .build()
```

**Comment by CosmicHorrorDev** [comment]
I'm gonna go ahead and close this, as there's nothing for us to do on this library's end at this point
